services:
  identity-api:
    build:
      context: ./UI
      dockerfile: Dockerfile
    image: seminar-identity-api
    ports:
      - "8080:8080"  # Map HTTP port
      - "8081:8081"  # Map HTTPS port
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - GoogleAuthSettings__ClientId=${GOOGLE_CLIENT_ID}
      - GoogleAuthSettings__ClientSecret=${GOOGLE_CLIENT_SECRET}
      - AllowedHosts=${CORS_ALLOWED_ORIGINS}

