FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0-jammy-arm64v8 AS base
WORKDIR /app
# http port
EXPOSE 8080
# https port 
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
    ARG TARGETARCH
WORKDIR /src
COPY ["IA03/IA03.csproj", "IA03/"]
RUN dotnet restore --arch $TARGETARCH
COPY . .
WORKDIR "/src/IA03"
RUN dotnet build "./IA03.csproj" -c Release -o /app/build --arch $TARGETARCH

FROM --platform=$BUILDPLATFORM build AS publish
ARG TARGETARCH
RUN dotnet publish "IA03.csproj" -c Release -o /app/publish --arch $TARGETARCH 

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "IA03.dll"]