name: Run Playwright Tests 🎭

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout ⚙️
        uses: actions/checkout@v4
    
      - name: Make .env file 📄
        run: |
          echo "GOOGLE_CLIENT_ID=907759503353-5v3aon6s0fdhklod6qsc6bedrt3vketk.apps.googleusercontent.com" >> .env
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
          
          echo "JWT_SECRET=test-secret-key" >> .env
          echo "JWT_ISSUER=http://localhost:8080" >> .env
          echo "JWT_AUDIENCE=http://localhost:8080" >> .env

          echo "POSTGRES_HOST=localhost" >> .env
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=postgres" >> .env
          echo "POSTGRES_DB=testdb" >> .env

      # Start apis and database
      - name: Start containers 🐳
        run: |
          docker compose -f docker-compose.yml up -d

      - name: Install node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Make UI .env file
        run: |
          echo "VITE_IDENTITY_API_URL=http://localhost:8080" > UI/.env
          echo "VITE_GOOGLE_CLIENT_ID=907759503353-5v3aon6s0fdhklod6qsc6bedrt3vketk.apps.googleusercontent.com" >> UI/.env
          echo "VITE_GOOGLE_REDIRECT_URI=http://localhost:5173/oauth2/google/redirected" >> UI/.env
          echo "VITE_TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> UI/.env
          echo "VITE_TMDB_API_URL=https://api.themoviedb.org/3" >> UI/.env
          echo "VITE_TMDB_ACCESS_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJiNzQ1ZTQyZDI4MjE2Mjk0NGJkZWU1YjA5YjM1Mjk1OCIsIm5iZiI6MTczMzg2NTE2My41MzEwMDAxLCJzdWIiOiI2NzU4YWVjYjk5MzU5YjA0NjhhNDc0N2MiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.WzMAVBJs0tAWE2n1cu6wh2591xPm8QX6D8eNkTmMF38" >> UI/.env    

      - name: Run UI App 🚀
        run: |
          cd UI
          npm install
          npm run dev 

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
  
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30